### ISSUE TITLE
`last_run` displays as 1min prior to scheduled.

### ISSUE THREAD

**Issue by jarekwg** [uptick/bronski#3]
Job `last_run` shows that they run one minute prior to when they're scheduled. So, actually, when I schedule for 4AM, it says it last ran at 1:59PM.

**Comment by funkybob** [comment]
`mark_run` uses `Now()` which will get the current time from the DB server.

Are you certain your DB server's clock is in sync with you app server?

**Comment by jarekwg** [comment]
How do i check?

**Comment by funkybob** [comment]
What times do your logs show the bronski runner starting its work?

**Comment by funkybob** [comment]
After more investigation, this is due to microseconds in datetime.now().

Bronski checks if the crontab time is in the next minute by using:
```
if (next_run - now) < timedelta(minutes=1):
```
Since `now` includes the microseconds, for jobs supposed to run in the _next_ minute, this tests True.
