### ISSUE TITLE
Scheduling quirk when updating in admin.

### ISSUE THREAD

**Issue by jarekwg** [uptick/bronski#4]
If I change cron string in admin to `* * * * *`, it'll start immediately getting picked up and running every minute. But if I try to be any more specific (eg setting minute to just a couple mins after current time), it won't run. _Could_ be related to either #2 or #3, but even trying `25 * * * *` when the time was 1:19PM, didn't result in Job getting picked up. I tried setting the last_run time to waay in the past, just in case the system thought it had already run recently and didn't want to run again, but no dice.

**Comment by funkybob** [comment]
Does it _ever_ run again? Or just not the next expected run cycle?
